### ISSUE TITLE
IQueryable

### ISSUE THREAD

**Issue by ranouf** [zzzprojects/EntityFramework-Plus#164]
hello,

I added the the nugget package Z.EntityFramework.Plus.EFCore
And using Z.EntityFramework.Plus; in the cs file.

'IQueryable<ShopCategory>' does not contain a definition for 'IncludeFilter' and no extension method 'IncludeFilter' accepting a first argument of type 'IQueryable<ShopCategory>' could be found (are you missing a using directive or an assembly reference?)	

I would like to IncludeFilter on a Queryable<ShopCategory>. Is it possible?

**Comment by JonathanMagnan** [comment]
Hello @ranouf ,

See the following answer about IncludeFilter && EFCore: https://github.com/zzzprojects/EntityFramework-Plus/issues/156#issuecomment-295399216

In short, it's currently `impossible` since EF Core have a N+1 issue even in the version 2.x preview. So even if all the code is here and working, I obviously don't want to release a feature that will bring performance issue.

Best Regards,

Jonathan

**Comment by ranouf** [comment]
Too bad :( 

Thank for your answer

**Comment by mhosman** [comment]
This is fixed in EF Core 2.1.0 preview 2?

**Comment by JonathanMagnan** [comment]
Hello @mhosman ,

We are still unable to make this feature work in the latest EF Core version.

We will try it again once EF Core 2.1.0 will be released.

Best Regards,

Jonathan

**Comment by vertonghenb** [comment]
@JonathanMagnan Should be fixed in 2.1, no?
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.1#optimization-of-correlated-subqueries

**Comment by JonathanMagnan** [comment]
Not for what's required for this feature.

Here is our test example we are waiting to work:

```csharp
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Z.Test.EntityFramework.Plus;

namespace Z.EntityFramework.Plus.Lab.EFCore20
{
    public static class Request_IncludeFilter
    {
        public static void Execute()
        {
            // CLEAN
            using (var ctx = new EntityContext())
            {
                ctx.Childs.RemoveRange(ctx.Childs);
                ctx.Parents.RemoveRange(ctx.Parents);
                ctx.SaveChanges();
            }

            // SEED
            using (var ctx = new EntityContext())
            {
                for (var j = 0; j < 5; j++)
                {
                    var parent = ctx.Parents.Add(new Parent {ColumnInt = 1}).Entity;
                    parent.Childs = new List<Child>();

                    for (var i = 0; i < 5; i++)
                    {
                        parent.Childs.Add(new Child {ColumnInt = i});
                    }
                }

                ctx.SaveChanges();
            }

            // TEST
            using (var ctx = new EntityContext())
            {
                var parents = ctx.Parents
                    .Select(x => new
                    {
                        parent = x,
                        Child = x.Childs.Where(y => y.ColumnInt > 2)
                    })
                    .ToList();
            }
        }

        public class EntityContext : DbContext
        {
            public EntityContext()
            {
                Database.EnsureCreated();
            }

            public DbSet<Parent> Parents { get; set; }
            public DbSet<Child> Childs { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlServer(new SqlConnection(My.Config.ConnectionStrings.TestDatabase));

                base.OnConfiguring(optionsBuilder);
            }
        }

        public class Parent
        {
            public int Id { get; set; }
            public int ColumnInt { get; set; }
            public List<Child> Childs { get; set; }
        }

        public class Child
        {
            public int Id { get; set; }

            public int ColumnInt { get; set; }

            public int ParentId { get; set; }
        }
    }
}
```

As you will notice, the following SQL is executed:

```sql
SELECT [x].[Id], [x].[ColumnInt]
FROM [Parents] AS [x]
```

and every child is a QueryProviderMethod that will execute their own SQL:

```sql
exec sp_executesql N'SELECT [y].[Id], [y].[ColumnInt], [y].[ParentId]
FROM [Childs] AS [y]
WHERE ([y].[ColumnInt] > 2) AND (@_outer_Id = [y].[ParentId])',N'@_outer_Id int',@_outer_Id=7841
```

which still lead to a N+1 queries.

When this example will work correctly, we will be able to look at this feature again.

Best Regards,

Jonathan
