### ISSUE TITLE
Batch Update conditional expression with null value

### ISSUE THREAD

**Issue by panizza** [zzzprojects/EntityFramework-Plus#226]
Hi again, I have a problem with Update method.

I've an update query which looks like this
```csharp
ctx.Users
    .Where(x => columnsint.Contains(x.ColumnInt))
    .Update(u => new User
    {
        STATUS = update.updateStatus ? values.status : u.STATUS,
        FIRST_NAME = update.updateFirstName ? values.firstName : u.FIRST_NAME,
        LAST_NAME = update.updateLastName ? values.lastName : u.LAST_NAME,
        IdRole = update.updateRole ? values.roleId: u.IdRole
    });
```
and everything works just fine.
But when one of the new values is null I get
```
ArgumentNullException: value cannot be null. Parameter name 'value'
   in System.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
   in System.Data.Entity.Core.Objects.ObjectParameter..ctor(String name, Object value)
   in Z.EntityFramework.Plus.BatchUpdate.GetInnerValues[T](IQueryable`1 query, Expression`1 updateFactory, SchemaEntityType`1 entity) in C:\Users\apa\Documents\Visual Studio 2015\Projects\EntityFramework-Plus-1.6.17\src\shared\Z.EF.Plus.BatchUpdate.Shared\BatchUpdate.cs:riga 1039
   in Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory) in C:\Users\apa\Documents\Visual Studio 2015\Projects\EntityFramework-Plus-1.6.17\src\shared\Z.EF.Plus.BatchUpdate.Shared\BatchUpdate.cs:riga 203
   in Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder) in C:\Users\apa\Documents\Visual Studio 2015\Projects\EntityFramework-Plus-1.6.17\src\shared\Z.EF.Plus.BatchUpdate.Shared\Extensions\Update.cs:riga 52
   in Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory) in C:\Users\apa\Documents\Visual Studio 2015\Projects\EntityFramework-Plus-1.6.17\src\shared\Z.EF.Plus.BatchUpdate.Shared\Extensions\Update.cs:riga 26
```

[Here](https://1drv.ms/u/s!Avu5Bks_UJbHiO8xqbanay0qNEOvTw) you can find a full example (if you need one)

Thanks

**Comment by JonathanMagnan** [comment]
Hello @panizza ,

Thank you for reporting, we will look at this issue today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @panizza ,

The issue has been fixed.

It will be available on our next release that will happen on Monday or before.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @panizza ,

The v1.6.18 has been released.

The conditional issue should be fixed.

Please reopen if you still have the issue.

Best Regards,

Jonathan

**Comment by panizza** [comment]
Hello @JonathanMagnan,
the issue is not resolved. 
I get an ArgumentNullException in BatchUpdate.cs:1070.
I guess the reason is that the System.Data.Entity.Core.Objects.ObjectParameter constructor explicitly states 
```
        //   value:
        //     The initial value (and inherently, the type) of the parameter.
        //
        // Exceptions:
        //   T:System.ArgumentNullException:
        //     If the value of either argument is null.
```
#228 fixes this issue

Thanks
Andrea

**Comment by JonathanMagnan** [comment]
Hello @panizza ,

Thank you for your contribution.

The v1.6.19 has been released with your pull.

Best Regards,

Jonathan
