### ISSUE TITLE
Exception thrown finding ObjectQuery when running Batch Delete in Unit Test

### ISSUE THREAD

**Issue by APErebus** [zzzprojects/EntityFramework-Plus#387]
This is almost identical to #256, but instead of the batch update, it's the batch delete that's throwing the issue...

```
System.Exception : Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com
   at Z.EntityFramework.Plus.InternalExtensions.GetObjectQuery[T](IQueryable`1 query)
   at Z.EntityFramework.Plus.InternalExtensions.GetDbContext[T](IQueryable`1 query)
   at Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

I was hoping the solution for #256 would also be there on the BatchDeleteManager, but it's not :(

**Comment by JonathanMagnan** [comment]
Hello @APErebus ,

Thank you for reporting, we will look at it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @APErebus ,

The v1.8.6 has been released.

The option `IsInMemoryQuery` has been added to the `BatchDeleteManager`.

Best Regards,

Jonathan

**Comment by APErebus** [comment]
@JonathanMagnan thanks!

**Comment by JonathanMagnan** [comment]
Hello @APErebus ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

**Comment by APErebus** [comment]
Hi @JonathanMagnan,

Unfortunately this hasn't resolved the issue. I can't re-open the issue as you closed it, but I'm still getting the same error stack trace.

Looking through the changeset that added the property, it seems like it's not set up correctly. Specifically https://github.com/zzzprojects/EntityFramework-Plus/blob/d5ccc491e9e0980c8ef2e2bd532574fdc83b6deb/src/shared/Z.EF.Plus.BatchDelete.Shared/BatchDelete.cs#L196 is still trying to get the ObjectContext if it's an in-memory query.

ALso it appears that the line getting the objectcontext before ALWAYS runs, so the property does nothing

**Comment by JonathanMagnan** [comment]
Hello @APErebus ,

You are right, we successfully reproduced it with your test project.

We will look at how we can handle it. That's a little bit different for `BatchDelete` since we need to actually delete it from the set. So we need to retrieve the DbContext.

If we come out with a solution such as inheriting the `ObservableCollection` to add a property about the current context could be a viable solution for you?

**Comment by APErebus** [comment]
@JonathanMagnan This repo replicates the issue with our mocking setup https://github.com/APErebus/ef-batch-delete-testing

**Comment by JonathanMagnan** [comment]
Hello @APErebus ,

Thank you for the project,

We are started to investigate it. However, I'm not sure how we can handle it at this moment.

We will continue to look at it tomorrow.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @APErebus ,

Just to let you known that we investigated this issue but we are currently unsure how to handle it since we cannot retrieve the information required on our side to make this feature work.

We will continue to investigate it.

Best Regards,

Jonathan

**Comment by APErebus** [comment]
@JonathanMagnan thank you for the contact. Appreciate your continued work. Ideally, it would be nice just not to error at all (so at lease the test could pass).

Personally I'm not too concerned with things being removed from the mock db context, but I understand other probably would be.

**Comment by 9566707474** [comment]
any update on the above issue.. please share me the sample mock code Bulk. delete

**Comment by JonathanMagnan** [comment]
Hello @9566707474 ,

On our side, we stoped the investigation about it. The problem is that our library needs an `ObjectQuery` to work but `NSubstitute` work differently and were not able to make our library compatible with it.

However, we support `Effort` and `InMemory`, so some alternative exists for your unit testing.

Best Regards,

Jon
