### ISSUE TITLE
Error. UpdateFromQuery with TPT.  (Z.EntityFramework.Plus.EF6 (v. 1.8.11))

### ISSUE THREAD

**Issue by cjmairair** [zzzprojects/EntityFramework-Plus#426]
I have the following TPT setup.

```
    public abstract class AnimalBase
    {
        public virtual int Id { get; set; }
        public virtual int Age { get; set; }
        // ....
    }

    public class Animal : AnimalBase
    {
        // ...
    }

    public class Dog : Animal{ /* ... */}
    public class Cat: Animal{ /* ... */}
```

When I try to do something like this:

`context.Animals.Where(...).Update(o => new Animal() { Age = age });`

I get an exception from Z.EntityFramework.Plus.EF6 (v. 1.8.11). 

`System.Data.SqlClient.SqlException: Invalid column name 'Id'`

(It seems like the exception happens before any SQL is even generated, because I ran SQL Profiler and didn't see anything. But that doesn't seem right, because the exception was a SqlException.)

**Comment by JonathanMagnan** [comment]
Hello @cjmairair ,

`Inheritance` is currently not supported in EF Plus.

However, [Entity Framework Extensions](https://entityframework-extensions.net/) already support them.

You can find some more info about what might happen to the support for this here: https://github.com/zzzprojects/EntityFramework-Plus/issues/269#issuecomment-433284291 

Let me know if that answered your question.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @cjmairair ,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

**Comment by cjmairair** [comment]
It does NOT work in EF Extensions either. I get the same behavior.

**Comment by JonathanMagnan** [comment]
Hello @cjmairair ,

I will make my developer look at it later today,

If it works, we will provide an online example, otherwise, we will fix it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @cjmairair ,

It seems our library support `UpdateFromQuery` with your scenario: https://dotnetfiddle.net/Rea74P

But doesn't yet with `DeleteFromQuery`. If I remember well, it was intended at first to avoid some mistake but perhaps we should relook this decision.

Do you need the `DeleteFromQuery` do work as well?

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Crossbow78 ,

Could you create your own issue with that? It will help to better follow it.

It's easier when creating a new issue and referencing when needed a similar issue.

Best Regards,

Jonathan

**Comment by cjmairair** [comment]
Yes, I do. The whole inheritance situation should be straightened out -
especially for how much this thing costs.

On Nov 13, 2018 1:54 PM, "Jonathan Magnan" <notifications@github.com> wrote:

Hello @cjmairair <https://github.com/cjmairair> ,

It seems our library support UpdateFromQuery with your scenario:
https://dotnetfiddle.net/Rea74P

But doesn't yet with DeleteFromQuery. If I remember well, it was intended
at first to avoid some mistake but perhaps we should relook this decision.

Do you need the DeleteFromQuery do work as well?

Best Regards,

Jonathan

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zzzprojects/EntityFramework-Plus/issues/426#issuecomment-438452453>,
or mute the thread

**Comment by JonathanMagnan** [comment]
Great,

My developer already started to look at it this morning.

I will give you an update next Monday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @cjmairair ,

The v3.16.12 has been released,

We fixed some issue that was still unsupported in our library, could you try it and let me know if everything works as expected?

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @cjmairair ,

Did you have the chance to test the latest version?

Best Regards,

Jonathan

**Comment by cjmairair** [comment]
It still doesn't work. I get the same error.

I know it's been a while. I just couldn't get around to testing this.

I'm using Z.EntityFramework.Plus.EF6 1.10.3.0 and Z.EntityFramework.Extensions 4.0.9.0.

**Comment by cjmairair** [comment]
Please re-open this issue.

**Comment by JonathanMagnan** [comment]
Hello @cjmairair ,

Let start by using the following Online Example: https://dotnetfiddle.net/Rea74P

Could you let me know what's not working? Can you reproduce the issue to give us some hint about where to start?

Best Regards,

Jonathan

**Comment by cjmairair** [comment]
[image: image.png]

**Comment by cjmairair** [comment]
I will take a look at the .NET Fiddle now.

**Comment by JonathanMagnan** [comment]
Just to let you know, the image didn't appear if you wanted to show something

**Comment by cjmairair** [comment]
Here's the image I was trying to upload.

![image](https://user-images.githubusercontent.com/29903939/67320392-09b27080-f4c3-11e9-8e53-3db94ce2f6e7.png)

**Comment by cjmairair** [comment]
I tried the .NET Fiddle and don't see the problem. I'll have to make a little local SQL Server database and test it out.

**Comment by JonathanMagnan** [comment]
hello @cjmairair 

Did you get the chance to test it out?

Looking forward to hearing from you, 

Jon
