### ISSUE TITLE
InvalidCastException when update with where in

### ISSUE THREAD

**Issue by ZeekoZhu** [zzzprojects/EntityFramework-Plus#524]
### Description
An `InvalidCastExpression` is thrown when using `UpdateAsync` with `WHERE IN`. For example:

```cs
var list = db.Posts.Where(x => postIds.Contains(x.Id)).ToListAsync();
// No problem

await db.Posts.Where(x => postIds.Contains(x.Id)).UpdateAsync(x => new Post { x.ViewCount = 0 });
// InvalidCastException
```

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlParameterExpression' to type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlConstantExpression'.
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitIn(InExpression inExpression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GetCommand(SelectExpression selectExpression)
   at Z.EntityFramework.Plus.BatchUpdate.CreateCommand(IQueryable query, IEntityType entity, List`1 values)
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.<>c__DisplayClass2_0`1.<UpdateAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at EFCorePlusSQLiteUpdateIssue.Program.Main(String[] args) in /home/zeeko/Projects/EFCorePlusSQLiteUpdateIssue/Program.cs:line 40
   at EFCorePlusSQLiteUpdateIssue.Program.<Main>(String[] args)
```

### Fiddle or Project
Reproduce: https://github.com/ZeekoZhu/EFCorePlusSQLiteUpdateIssue

### Further technical details
- EF version: 3.0.0
- EF Plus version: 3.0.11
- Database Provider: `microsoft.entityframeworkcore.sqlite` and `microsoft.entityframeworkcore.sqlserver`

**Comment by JonathanMagnan** [comment]
Hello @ZeekoZhu ,

Thank you for reporting, we will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @ZeekoZhu ,

Sorry for the long delay, we have been quite busy recently here.

When using `UpdateAsync`, you need to create an instance of the type since we use expression tree to find after property name & value.

```csharp
UpdateAsync(x =>  new Posts() { ViewCount = 0})
```

Let me know if that works successfully once you make this change.

Best Regards,

Jonathan

**Comment by syunakh** [comment]
it doesn't work for me. looks like Contains is problem. Future also throw the same issue if a few query have Contains

**Comment by JonathanMagnan** [comment]
Could you update your repository in this case?

My developer will go further in the request if that still fails.

**Comment by syunakh** [comment]
what do you mean?

just try to do request like that

`await db.Posts.Where(x => postIds.Contains(x.Id)).UpdateAsync(x =>  new Posts() { ViewCount = 0});`

or

```
var collection1 =  db.Posts.Where(x => postIds.Contains(x.Id)).Future();
var collection2 =  db.Posts2.Where(x => postIds.Contains(x.Id)).Future();

collection2.ToList();
```

**Comment by syunakh** [comment]
https://github.com/syunakh/zzzexception there is example

I hope you will fix it soon

**Comment by JonathanMagnan** [comment]
Assigned to my developer! He should be able to look at it today or next Monday.

**Comment by syunakh** [comment]
thank you. I hope today because now no one method of z.ef works if query has Contains, Any, All.
and we can't use this library :/

**Comment by JonathanMagnan** [comment]
Hello @syunakh ,

We didn't make it to fix it yesterday, but we have good news today.

Could you try the v3.0.12, it should be fixed in this new version.

Let us know if everything works as expected.

Best Regards,

Jonathan

**Comment by syunakh** [comment]
@JonathanMagnan it fixed the issue for Update but it have not fixed issue for Future()

I updated my repository

**Comment by JonathanMagnan** [comment]
Hello @syunakh ,

The v3.0.13 has been released.

I forget that we had 2 very similar (but still different code) methods and both needed the same fix.

Let me know if everything works as expected.

Best Regards,

Jonathan

**Comment by syunakh** [comment]
@JonathanMagnan  It works. thank you so much

**Comment by ZeekoZhu** [comment]
@JonathanMagnan Thank you!
